### ISSUE TITLE
core 3.1.2 does not use correct schema when sending alarm suspend message.

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_schema#107]
The validator sends this message:

```
Sent Alarm  {"mType":"rSMsg","type":"Alarm","ntsOId":"","xNId":"","xACId":"","xNACId":"","aSp":"Resume","mId":"6d56d25b-73af-4eb1-bffd-5dfad9c0bbb5","cId":"AA+BBCCC=DDDDL002","aCId":"A0302"}
```

Notice the "aSp" field, which reads "Resume". According the the docs (https://rsmp-nordic.github.io/rsmp_core/3.1.2/applicability/usage_of_json.html#alarm-messages) the "aSp" field is lower-case for core 3.1.2. The particular case for "resume" is not documented, but the other shown cases are lower-case.

**Comment by emiltin** [comment]
With #109, only "Suspend/Resume" is allowed for Alarm aSp for core >= 3.2.0.
For earlier core version, the spec uses "suspend/resume", but keep in mind that since exact casing was not explicitly required in earlier versions of the core spec, we schema also allows "Suspend/Resume" for these versions. That's we why no schema error was raised when sending the Alarm show in the origin issue above.

We should change the rsmp gem to use the recommended "suspend/resume" for core < 3.2.0.

**Comment by emiltin** [comment]
done
