### ISSUE TITLE
Add core 3.2.1

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#82]
Minor changes to datatypes: number instead of integer/long.

**Comment by otterdahl** [comment]
> Minor changes to datatypes: number instead of integer/long.

I think `number` is used instead of `long` and `real`.

`number` can be either integer or floating point. We've kept `integer` since we wanted the ability to explicitly define some values as integer. I don't think we use `long` or `real` in the TLC SXL.

The only change that affects the with Core 3.2.1 is the addition of `timestamp`. But the TLC SXL already use them since SXL 1.1.

**Comment by emiltin** [comment]
done
